import { icons } from "../constants";
export const DUMMY_DATA = [
  {
    id: 1,
    type: 'E-Wallet',
    name: "John Doe",
    isFavourite: true,
    email: "john.doe@example.com",
    image: icons.userDefault2,
  },
  {
    id: 2,
    type: 'E-Wallet',
    name: "Jane Smith",
    isFavourite: false,
    email: "jane.smith@example.com",
    image: icons.userDefault2,
  },
  {
    id: 3,
    type: 'bank',
    name: "Alice Johnson",
    isFavourite: false,
    email: "alice.johnson@example.com",
    image: icons.userDefault2,
  },
  {
    id: 4,
    type: 'bank',
    name: "Bob Brown",
    isFavourite: false,
    email: "bob.brown@example.com",
    image: icons.userDefault2,
  },
  {
    id: 5,
    type: 'bank',
    name: "Charlie Davis",
    isFavourite: true,
    email: "charlie.davis@example.com",
    image: icons.userDefault2,
  },
  {
    id: 6,
    type: 'E-Wallet',
    name: "Diana Green",
    isFavourite: true,
    email: "diana.green@example.com",
    image: icons.userDefault2,
  },
  {
    id: 7,
    type: 'E-Wallet',
    name: "Ethan White",
    isFavourite: true,
    email: "ethan.white@example.com",
    image: icons.userDefault2,
  },
  {
    id: 8,
    type: 'bank',
    name: "Fiona Black",
    isFavourite: true,
    email: "fiona.black@example.com",
    image: icons.userDefault2,
  },
  {
    id: 9,
    type: 'E-Wallet',
    name: "George Blue",
    isFavourite: true,
    email: "george.blue@example.com",
    image: icons.userDefault2,
  },
  {
    id: 10,
    type: 'E-Wallet',
    name: "Hannah Red",
    isFavourite: false,
    email: "hannah.red@example.com",
    image: icons.userDefault2,
  },
  {
    id: 11,
    type: 'bank',
    name: "Ian Yellow",
    isFavourite: true,
    email: "ian.yellow@example.com",
    image: icons.userDefault2,
  },
  {
    id: 12,
    type: 'E-Wallet',
    name: "Julia Pink",
    isFavourite: true,
    email: "julia.pink@example.com",
    image: icons.userDefault2,
  },
  {
    id: 13,
    type: 'bank',
    name: "Kevin Purple",
    isFavourite: false,
    email: "kevin.purple@example.com",
    image: icons.userDefault2,
  },
  {
    id: 14,
    type: 'bank',
    name: "Laura Orange",
    isFavourite: true,
    email: "laura.orange@example.com",
    image: icons.userDefault2,
  },
  {
    id: 15,
    type: 'E-Wallet',
    name: "Michael Grey",
    isFavourite: true,
    email: "michael.grey@example.com",
    image: icons.userDefault2,
  },
  // Add more users here if needed...
];
